spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: com.example.pipelinrkafka.weatherprovider

example:
  messagebus:
    kafka:
      # True to enable message bus support using Kafka.
      enabled: true

      # Request timeout.
      timeout: 60000

      # Number of requests this service can process simultaneously. Only has effect
      # if `example.messagebus.topic.self.request` has value.
      concurrency: 10

      # The compression type.
      compression:
        type: none
      topic:
        self:
          # The request topic of this service. Uncomment to enable requests to it from other services.
          request: com.example.pipelinrkafka.weatherprovider.request

          # The reply topic with responses from other services. Disabled since this service does not request
          # other services, hence doesn't expect any replies.
          # reply: com.example.pipelinrkafka.weatherprovider.reply

          # How many partitions do the request and reply topics have. This number defines how many instances
          # of this service can run simultaneously.
          partitions: 5

        # Add request topics of other services below to send them requests.
        # webapi: com.example.webapi.request
